language: ruby
cache: bundler
rvm:
  - 2.2.7
matrix:
  allow_failures:
    - 2.1
    - 2.3.4
    - 2.4.1
    - jruby
    - rbx-2
  fast_finish: true
install:
  - travis_retry bundle install
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --assume-extension --check-favicon --check-html --allow-hash-href
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
